# Generated by Django 2.2.1 on 2019-05-14 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 13, 32, 58, 602226)),
        ),
    ]
