# Generated by Django 2.2 on 2019-05-19 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 12, 20, 51, 643555)),
        ),
    ]
