# Generated by Django 2.2.1 on 2019-05-21 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190519_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('model_description', models.TextField(blank=True)),
                ('order_file', models.FileField(upload_to='orders_files')),
                ('order_time', models.DateTimeField(default=datetime.datetime(2019, 5, 21, 18, 35, 47, 721583))),
                ('order_type', models.CharField(choices=[('M', '3D modeling'), ('P', '3D printing')], default='P', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 21, 18, 35, 47, 721583)),
        ),
    ]
