# Generated by Django 2.2.1 on 2019-05-22 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190521_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 9, 53, 57, 844738)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 9, 53, 57, 844738)),
        ),
    ]
