# Generated by Django 2.2.1 on 2019-05-22 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190522_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('order_description', models.TextField(blank=True)),
                ('order_file', models.FileField(upload_to='modeling_orders_files')),
                ('order_time', models.DateTimeField(default=datetime.datetime(2019, 5, 22, 11, 58, 25, 552948))),
            ],
        ),
        migrations.CreateModel(
            name='PrintingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_email', models.EmailField(max_length=254)),
                ('material', models.CharField(choices=[('PLA', 'PLA'), ('ABS', 'ABS'), ('PETG', 'PETG'), ('NEYLON', 'NEYLON'), ('FLEX', 'FLEX')], max_length=10)),
                ('quality', models.CharField(choices=[('HIGH', 'High, 0.1mm layer height'), ('MEDIUM', 'Medium, 0.2mm layer height'), ('LOW', 'Low, 0.3mm layer height')], max_length=6)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('order_file', models.FileField(upload_to='printing_orders_files')),
                ('order_time', models.DateTimeField(default=datetime.datetime(2019, 5, 22, 11, 58, 25, 552948))),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 11, 58, 25, 552948)),
        ),
    ]
